### ISSUE TITLE
How to add Lottie Framework in bitrise -> XCode?

### ISSUE THREAD

**Issue by blessinasavvyan** [timbru31/cordova-plugin-lottie-splashscreen#132]
# Bug report
## What steps will reproduce the problem?
1.Installed cordova-plugin-lottie-splashscreen and @ionic-native/lottie-splash-screen
2.Made sure, it matches all these versions -> Cordova-ios Version -> 5.1.1 , Cordova -> 9.0.0, Swift Version - 4.2
3.  Updated the lottie Animations preferences [LottieAnimationLocation, Swift Version] in config.xml 
## What do you see instead?

<img width="722" alt="Screenshot 2019-12-14 at 2 28 27 AM" src="https://user-images.githubusercontent.com/35607401/70831786-71c56900-1e19-11ea-9dfa-1742f87de7ba.png">

## Log file of the issue/error
⚠️  ld: directory not found for option '-F/Users/vagrant/Library/Developer/Xcode/DerivedData/Tranzport-gcgwpnomolsykbeafjfulbksxcpu/Build/Intermediates.noindex/ArchiveIntermediates/Tranzport/BuildProductsPath/Release-iphoneos/lottie-ios'
❌  ld: framework not found Lottie
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
Exit status: 65

## Version information
Cordova-ios Version -> 5.1.1 , Cordova -> 9.0.0, Swift Version - 4.2

## Checklist

-   [ ] If there is a (potential) plugin conflict, I've identified the conflicting plugin
-   [ ] I have added a valid version output
-   [x] I have attached necessary information like a screenshot, example project or videos

**Comment by egonzalez-T** [comment]
Having the same issue

**Comment by timbru31** [comment]
How did you guys build the app? Normally `cordova build ios` should take care to install the required framework.

**Comment by blessinasavvyan** [comment]
> How did you guys build the app? Normally `cordova build ios` should take care to install the required framework.

We are using Bitrise CI/CD for our mobile App, where we define the scripts in bitrise.yml to build our    
app.
**Bitrise.yml file:** 

- We added platforms with **ionic cordova platform add ios**
- And then build the app through _fastlane Beta_ and it sets up the XCode Project with the provisioning profiles and code-signing thing using _fastfile_ and produces the build
- While it runs the XCode, it looks for **lottie-framework**, even though we installed cordova-plugin-lottie-splashscreen and @ionic-native/lottie-splash-screen
![image](https://user-images.githubusercontent.com/35607401/71083881-0f25f180-21ba-11ea-9cd7-f77cfffda0ac.png)

In Local Xcode Error, 
![image](https://user-images.githubusercontent.com/35607401/71083938-249b1b80-21ba-11ea-94b6-c280519f8452.png)

If I drag the lottie framework from node-modules -> Xcode configuration under Frameworks and Libraries manually, it works.

whereas, bitrise runs the xcode and where we don't have option to add lottie framework automatically.

Please let us know the solution, how to automatically add the lottie Framework into XCode Project, either in local or Bitrise.

**Comment by timbru31** [comment]
I have no experiences with Bitrise or Fastlane. You would really help me if you can share an (anonymized) Fastlane or Bitrise configuration file, so I can setup the build process, too.

**Comment by blessinasavvyan** [comment]
> I have no experiences with Bitrise or Fastlane. You would really help me if you can share an (anonymized) Fastlane or Bitrise configuration file, so I can setup the build process, too.

you can replicate bitrise locally following these steps

**Comment by egonzalez-T** [comment]
@timbru31 I can replicate the the error locally. I add the plugin via `ionic cordova plugin add`. Swift version is specified in config.xml and I am running ```Ionic:

   Ionic CLI                     : 5.4.4 (/Users/emmanuelgonzalez/.npm-packages/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.0
   @angular-devkit/build-angular : 0.801.1
   @angular-devkit/schematics    : 8.1.1
   @angular/cli                  : 8.1.1
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : browser 5.0.4, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-webview 2.5.3, (and 28 other plugins)```

When I try to either run it with ionic cordova build ios or through Xcode I get the above errors.

**Comment by timbru31** [comment]
Ionic is something I can easily try - although Ionic should just wrap the Cordova CLI

**Comment by egonzalez-T** [comment]
Any info I can give you to be more clear?

**Comment by egonzalez-T** [comment]
<img width="1336" alt="Screen Shot 2019-12-18 at 4 44 45 PM" src="https://user-images.githubusercontent.com/26878780/71187301-d08d4700-224c-11ea-920e-37d9516ac34b.png">

I think my issue was that the header files were not aligned between the release and debug fields. After aligning them it is working. Thanks for the help

**Comment by timbru31** [comment]
I am unable to reproduce this issue. I've setup a Bitrise account and added the example app - it correctly auto detected Cordova and successfully built both the Android and iOS apps. Both included the required lottie framework.
I've marked the app as public: https://app.bitrise.io/app/526cf252237e5100 so this can be used as a reference.

This is the default bitrise.yml file from https://app.bitrise.io/build/5273c5a122837afa:
```
---
format_version: '8'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: cordova
trigger_map:
- push_branch: "*"
  workflow: primary
- pull_request_source_branch: "*"
  workflow: primary
workflows:
  primary:
    steps:
    - activate-ssh-key@4.0.3:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@4.0.17: {}
    - script@1.1.5:
        title: Do anything with Script step
    - certificate-and-profile-installer@1.10.1: {}
    - npm@1.1.0:
        inputs:
        - workdir: "$CORDOVA_WORK_DIR"
        - command: install
    - generate-cordova-build-configuration@0.9.6: {}
    - cordova-archive@2.1.0:
        inputs:
        - platform: "$CORDOVA_PLATFORM"
        - target: emulator
        - workdir: "$CORDOVA_WORK_DIR"
    - deploy-to-bitrise-io@1.9.2: {}
app:
  envs:
  - opts:
      is_expand: false
    CORDOVA_WORK_DIR: example
  - opts:
      is_expand: false
    CORDOVA_PLATFORM: ios,android
```
